{% set name = "dp-accounting" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9938c4c2985ebb7aa480a637ea18f605286f0b698645e6d6895e9bb05b7c1d00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - absl-py >=1.0,<2.dev0
    - attrs >=22,<24
    - dm-tree >=0.1.8,<0.2.dev0
    - mpmath >=1.2,<2.dev0
    - numpy >=1.21,<3.0
    - scipy >=1.7,<2.dev0

test:
  imports:
    - dp_accounting
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google/differential-privacy/
  summary: Tools for tracking differential privacy budgets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
